# Generated by Django 3.0.6 on 2020-06-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='feautred',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
