# Generated by Django 3.0.6 on 2020-06-02 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobprofile', '0002_jobprofile_feautred'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobprofile',
            old_name='feautred',
            new_name='featured',
        ),
    ]
