# Generated by Django 3.0.6 on 2020-06-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsector',
            name='featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
