# Generated by Django 3.0.6 on 2020-06-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsector', '0002_jobsector_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('overview', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='jobsector',
            name='categories',
            field=models.ManyToManyField(to='jobsector.Jobcategory'),
        ),
    ]
