# Generated by Django 3.0.6 on 2020-06-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsector', '0003_auto_20200608_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
