# Generated by Django 3.0.6 on 2020-06-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsector', '0004_jobcategory_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsector',
            old_name='categories',
            new_name='category',
        ),
    ]
