# Generated by Django 3.0.6 on 2020-06-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsector', '0006_jobprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobprofile',
            old_name='overview',
            new_name='Coaching_institution',
        ),
        migrations.RemoveField(
            model_name='jobprofile',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='jobprofile',
            name='title_main',
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='hiring',
            field=models.TextField(default='yes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='job_description',
            field=models.TextField(default='yes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='locations',
            field=models.TextField(default='nearby'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='qualification',
            field=models.TextField(default='graduation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='responsibilties',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='salary',
            field=models.TextField(default='as per market standard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='skills',
            field=models.TextField(default='latest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='summary',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
